//HEADER ACTIONS
export const HEADER_INPUT_VALUE = "HEADER_INPUT_VALUE";
export const HEADER_CLICK_TOGGLE_INPUT = "HEADER_CLICK_TOGGLE_INPUT";
export const HEADER_TOGGLE_MODAL_LOGIN = "HEADER_TOGGLE_MODAL_LOGIN";

//MODAL ACTIONS
export const MODAL_CHECKED = "MODAL_CHECKED";
export const MODAL_INPUT_VALUE = "MODAL_INPUT_VALUE";
export const MODAL_CHECKED_REGIS_AUTHO = "MODAL_CHECKED_REGIS_AUTHO";
